### ISSUE TITLE
Fix gitignore

### ISSUE THREAD

**Issue by BrunoMPedraza** [BrunoMPedraza/RTS-SYSTEM-API#12]
Try with git rm -r logs/ on main
We truly have to solve this issue is turning us crazy.

**Comment by federicoPedraza** [comment]
This issue was resolved at commit fceb04b
https://github.com/BrunoMPedraza/RTS-SYSTEM-API/blob/377df12f4f0342676d632f3c1fc0a0bc675b5152/.gitignore
